
language: c

matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      dist: trusty
      sudo: false
    - os: osx
      osx_image: xcode7.2

compiler:
  - gcc
  - clang

env:
  global:
    - LD_LIBRARY_PATH: /usr/local/lib

os:
  - linux
  - osx

# whitelist
branches:
  only:
    - master

addons:
  apt:
   packages:
     - tree
     - wget
     - zip
     - libsdl1.2-dbg
     - libsdl1.2-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install tree sdl; fi

before_script:
  - tree -CFL 3

script:
  - make
  - tree -CFL 3
