
language: c

matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.2

compiler:
  - gcc

os:
  - linux
  - osx

# whitelist
branches:
  only:
    - master

addons:
  apt:
   packages:
     - tree
     - wget
     - zip
     - libsdl1.2-dbg
     - libsdl1.2-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install tree sdl; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y 'ppa:zoogie/sdl2-snapshots' &&  sudo apt-get update -qq && sudo apt-get install -qq -y libsdl2-dev cppcheck; fi

before_script:
  - echo "Data:" && ls -al;
  - tree -CFL 3

script:
  - make
  - tree -CFL 3
