
language: c

matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      dist: trusty
      sudo: false
    - os: osx
      osx_image: xcode7.2

services:
  - docker

compiler:
  - gcc
  - clang

env:
  global:
    - LD_LIBRARY_PATH: /usr/local/lib

os:
  - linux
  - osx

# whitelist
branches:
  only:
    - master

addons:
  apt:
   packages:
     - tree
     - wget
     - zip
     - build-essential
     - doxygen

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install tree; fi

before_script:
  - tree -CFL 3

script:
  - make
  - tree -CFL 3

after_script:
  - make debian
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then dpkg -i distribution/debian/bomberman.deb && which client && which server; fi